# Training settings
devices: 1  # Distributed training device number
debug: false  # Run in debug mode
learning_rate: 1e-5  # Learning rate
learning_rate_flow: 3e-4  # Learning rate for flow
learning_rate_decay: 5e-4  # Learning rate decay
run_finetuning: false  # Run fine-tuning
max_epochs: 50  # Maximum number of epochs
flow_finetune: 0  # Number of warmup epochs
batch_size: 4  # Batch size per GPU
epoch_length: 1250  # Length of an epoch in iterations
learning_rates: 1e-5 # List of learning rates to grid search
resume: true  # Resume from existing checkpoints
use_best_model: false  # Use the best model
camera_num: 2  # Number of cameras
gradient_accumulation_steps: 1  # Gradient accumulation steps

# Data module settings
data_root_dir:  # Root directories of the data
  - "../../data_all/data1"
  - "../../data_all/data3"
data_root_dir_test:  # Data directories for testing
  - "../../data_all/data4"
data_root_dir_debug:  # Data directories for debugging
  - "../../data_all/data_debug"
num_workers: 4  # Number of workers for data loading
image_size: [480, 640]  # Image size (width, height)
pcd_with_rgb: false  # Use RGB with PCD
scale: 0.875  # Image scaling factor
seed: 42  # Random seed
experiment: null  # Experiment name
dataset: "mgn"  # Dataset name

# Uncertainty settings
prob_baseline: lh  # Baseline vector (post, lh, or None)
certainty_budget: "constant"  # Certainty budget
entropy_weight: 1e-6  # Weight for entropy regularizer
flow_layers: 8  # Number of flow layers
point_backbone: pointnext-s  # Point backbone (pointnet, pointnext, or spotr)
ckpt: epoch=77-step=8658 # Checkpoint to load

# Flow model settings
hidden_feat_flow: 512  # Hidden feature size for the flow
embedding_dim: 240  # Embedding dimension for vmfContact
backbone: "clip"  # Backbone model (clip, vits, vitb, vitl, vitg, resnet)
flow_type: "resflow"  # Flow model type (resflow or glow)
