# Training settings
devices: 4  # Distributed training device number
debug: false  # Run in debug mode
learning_rate: 1e-4  # Learning rate
learning_rate_flow: 3e-4  # Learning rate for flow
learning_rate_decay: 5e-4  # Learning rate decay
run_finetuning: false  # Run fine-tuning
max_epochs: 20000  # Maximum number of epochs
flow_finetune: 0  # Number of warmup epochs
batch_size: 4  # Batch size per GPU
epoch_length: 1250  # Length of an epoch in iterations
resume: true  # Resume from existing checkpoints
use_best_model: false  # Use the best model
camera_num: 2  # Number of cameras
gradient_accumulation_steps: 1  # Gradient accumulation steps

# Data module settings
num_workers: 10  # Number of workers for data loading
image_size: [480, 640]  # Image size (width, height)
pcd_with_rgb: false  # Use RGB with PCD
scale: 0.875  # Image scaling factor
seed: 42  # Random seed
dataset: "mgn"  # Dataset name

# Uncertainty settings
prob_baseline: lh  # Baseline vector (post, lh, or None)
certainty_budget: "constant"  # Certainty budget
entropy_weight: 1e-6  # Weight for entropy regularizer
flow_layers: 8  # Number of flow layers
point_backbone: pointnext-b  # Point backbone (pointnet, pointnext, or spotr)
ckpt: "epoch=112-step=86558"

# Flow model settings
# hidden_feat_flow: 512  # Hidden feature size for the flow
embedding_dim: 240  # Embedding dimension for vmfContact
backbone: "clip"  # Backbone model (clip, vits, vitb, vitl, vitg, resnet)
flow_type: "resflow"  # Flow model type (resflow or glow)
